Bumped version to 2.1.0
divio/aldryn-sso pull request #79
Opened 2022-03-31 13:33 UTC by FinalAngel

- Add Django 4.0 support
- Fiyes https://github.com/divio/aldryn-sso/issues/78

2022-04-02 12:22 UTC, GaretJax requested changes

2022-04-04 09:16 UTC, FinalAngel commented on setup.py
> -    'itsdangerous',
aldryn-sso depends on django-simple-sso which in return pins it: https://github.com/divio/django-simple-sso/blob/master/setup.py#L9

2022-04-04 09:18 UTC, FinalAngel commented on tests/requirements.txt
> +https://github.com/FinalAngel/django-app-helper/archive/refs/heads/develop.zip#egg=django-app-helper
They are working on it, but as django CMS does not yet support Django 4.0 it will take some time until it is properly released. Once done we have to update all our aldryn addons anyhow to it. I marked it as a todo for myself. The last release of django-app-helper was December 2020

2022-04-04 09:20 UTC, FinalAngel commented on setup.cfg
> +max-line-length = 119
👍

2022-04-04 09:20 UTC, FinalAngel commented on aldryn_sso/views.py
> +    from django.utils.http import url_has_allowed_host_and_scheme as is_safe_url, urlencode
👍

2022-04-06 08:56 UTC, merged